## @file
# GNU/Linux makefile for 'BuildFatImage' module build.
#
ARCH ?= IA32
MAKEROOT ?= ..

APPNAME = BuildFatImage

OBJECTS = BuildFatImage.o

include $(MAKEROOT)/Makefiles/app.makefile
